### ISSUE TITLE
Exception while adding new data source

### ISSUE THREAD

**Issue by stefanoborini** [force-h2020/force-wfmanager#123]
Happens when creating a new data source and the parameter names have been set already.
I suspect it's because it tries to set the value but the available values is still empty

```
ERROR:traits:Exception occurred in traits notification handler for object: <force_bdss.core.workflow.Workflow object at 0x122f8f780>, trait: data_sources_items, old value: [], new value: [<enthought_example.example_data_source.example_data_source_model.ExampleDataSourceModel object at 0x1237dc258>]
Traceback (most recent call last):
  File "/Users/sborini/.edm/envs/force35/lib/python3.5/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/sborini/.edm/envs/force35/lib/python3.5/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/left_side_pane/workflow_model_view.py", line 120, in update_data_sources_representation
    for data_source in self.model.data_sources
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/left_side_pane/workflow_model_view.py", line 120, in <listcomp>
    for data_source in self.model.data_sources
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/left_side_pane/evaluator_model_view.py", line 140, in __init__
    self._create_slots_tables()
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/left_side_pane/evaluator_model_view.py", line 186, in _create_slots_tables
    self._fill_slot_rows(input_slots, output_slots)
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/left_side_pane/evaluator_model_view.py", line 219, in _fill_slot_rows
    for index, input_slot in enumerate(input_slots)
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/left_side_pane/evaluator_model_view.py", line 219, in <listcomp>
    for index, input_slot in enumerate(input_slots)
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/left_side_pane/evaluator_model_view.py", line 34, in __init__
    super(TableRow, self).__init__(*args, **kwargs)
  File "/Users/sborini/.edm/envs/force35/lib/python3.5/site-packages/traits/trait_types.py", line 2058, in _set
    self.error( object, name, value )
  File "/Users/sborini/.edm/envs/force35/lib/python3.5/site-packages/traits/trait_handlers.py", line 173, in error
    value )
traits.trait_errors.TraitError: The 'name' trait of an InputSlotRow instance must be '', but a value of 'p0' <class 'str'> was specified.
```

**Comment by stefanoborini** [comment]
Duplicate of #146
