### ISSUE TITLE
Unable to delete data sources

### ISSUE THREAD

**Issue by stefanoborini** [force-h2020/force-wfmanager#145]
There's a method missing so we can't delete data sources.
```
**Traceback (most recent call last):
  File "/Users/sborini/.edm/envs/force/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/sborini/.edm/envs/force/lib/python3.5/site-packages/traitsui/qt4/tree_editor.py", line 1337, in perform
    self.ui.do_undoable( self._perform, action )
  File "/Users/sborini/.edm/envs/force/lib/python3.5/site-packages/traitsui/ui.py", line 716, in do_undoable
    action( *args, **kw )
  File "/Users/sborini/.edm/envs/force/lib/python3.5/site-packages/traitsui/qt4/tree_editor.py", line 1362, in _perform
    method( info, object )
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/left_side_pane/workflow_tree.py", line 261, in delete_data_source
    self.workflow_mv.remove_data_source(object.model)
AttributeError: 'WorkflowModelView' object has no attribute 'remove_data_source'
**
```

**Comment by jjenthought** [comment]
Fixed by #171
