### ISSUE TITLE
concurrent futures seems to be installed also for python 3

### ISSUE THREAD

**Issue by stefanoborini** [force-h2020/force-wfmanager#179]
It appears that we get a python2 dependency when running on python3

```
Traceback (most recent call last):
  File "/Users/sborini/.edm/envs/force/bin/force_wfmanager", line 9, in <module>
    load_entry_point('force-wfmanager', 'gui_scripts', 'force_wfmanager')()
  File "/Users/sborini/.edm/envs/force/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/sborini/.edm/envs/force/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/Users/sborini/.edm/envs/force/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/Users/sborini/.edm/envs/force/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/gui/run.py", line 13, in <module>
    from force_wfmanager.wfmanager_plugin import WfManagerPlugin
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/wfmanager_plugin.py", line 8, in <module>
    from force_wfmanager.wfmanager_task import WfManagerTask
  File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/wfmanager_task.py", line 7, in <module>
    from concurrent.futures import ThreadPoolExecutor
  File "/Users/sborini/.edm/envs/force/lib/python3.5/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/Users/sborini/.edm/envs/force/lib/python3.5/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

**Comment by jjenthought** [comment]
Resolved by #182
