### ISSUE TITLE
Error when creating new execution layers [Linux Only]

### ISSUE THREAD

**Issue by jjenthought** [force-h2020/force-wfmanager#227]
Exception which came up using Ubuntu 18.04, I haven't been able to reproduce it.

Raised an exception when creating a new execution layer, if an existing execution layer has a datasource with an input name selected via combo box. Looks like the available variables list was empty somehow, and it failed when trying to assign the name when recreating datasources.
**traits.trait_errors.TraitError: The 'name' trait of an InputSlotRow instance must be '', but a value of 'n' <type 'str'> was specified.**
Traceback (most recent call last):
  File "/home/jj/.edm/envs/force-py27/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/home/jj/.edm/envs/force-py27/lib/python2.7/site-packages/traitsui/qt4/tree_editor.py", line 1338, in perform
    self.ui.do_undoable(self._perform, action)
  File "/home/jj/.edm/envs/force-py27/lib/python2.7/site-packages/traitsui/ui.py", line 731, in do_undoable
    action(*args, **kw)
  File "/home/jj/.edm/envs/force-py27/lib/python2.7/site-packages/traitsui/qt4/tree_editor.py", line 1363, in _perform
    method(info, object)
  File "/home/jj/Force/force-wfmanager/force_wfmanager/left_side_pane/workflow_tree.py", line 74, in wrap
    func(self, *args, **kwargs)
  File "/home/jj/Force/force-wfmanager/force_wfmanager/left_side_pane/workflow_tree.py", line 380, in new_layer
    self.workflow_mv.add_execution_layer(ExecutionLayer())
  File "/home/jj/Force/force-wfmanager/force_wfmanager/left_side_pane/workflow_model_view.py", line 57, in add_execution_layer
    self.model.execution_layers.append(execution_layer)
  File "/home/jj/.edm/envs/force-py27/lib/python2.7/site-packages/traits/trait_handlers.py", line 2501, in append
    raise excp
traits.trait_errors.TraitError: Each element of the 'name' trait of an InputSlotRow instance must be '', but a value of 'n' <type 'str'> was specified.

**Comment by stefanoborini** [comment]
I suspect unicode/str problems, so it's mostly a py3 problem

**Comment by jjenthought** [comment]
It’s just a pain that it wasn’t recreatable. It’s also some motivation to only replace modelviews which need replacing, rather than changing the whole thing every time a modelview is added/removed.
