### ISSUE TITLE
Launching the GUI locally fails: "the 'active_task' trait of a TaskWindowLayout instance" is None

### ISSUE THREAD

**Issue by nicolasap-dm** [force-h2020/force-wfmanager#289]
For some reason I've become unable to run the application on my computer (Ubuntu 16.04). This seems to be an issue related to my configuration, as Travis CI or other OS aren't affected: I have tried on a Windows VM and on @flongford 's macOS.

I am opening the issue for future memory and in case this turns out to be a general occurrence.

--

This happens, both when using the most recent `master`s and when using `master`s from one week ago (f8bf8cc here and [`4f4b601`](https://github.com/force-h2020/force-bdss/commit/4f4b6016b30826d9f20e4c4d127850e688b94d25) on bdss):
```
ndemitri@quokka:~/repos/force/master/force-wfmanager$ cd ../force-bdss ; edm run -e bootstrap -- python -m ci build-env ; edm run -e bootstrap -- python -m ci install; cd ../force-wfmanager/ ; edm run -e bootstrap -- python -m ci install

[...]

ndemitri@quokka:~/repos/force/master/force-wfmanager$ edm run -e force-py36 -- force_wfmanager
Traceback (most recent call last):
  File "/home/ndemitri/.edm/envs/force-py36/bin/force_wfmanager", line 11, in <module>
    load_entry_point('force-wfmanager', 'gui_scripts', 'force_wfmanager')()
  File "/home/ndemitri/.edm/envs/force-py36/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ndemitri/.edm/envs/force-py36/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ndemitri/.edm/envs/force-py36/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ndemitri/.edm/envs/force-py36/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ndemitri/repos/force/master/force-wfmanager/force_wfmanager/gui/run.py", line 45, in force_wfmanager
    profile=profile)
  File "/home/ndemitri/repos/force/master/force-wfmanager/force_wfmanager/gui/run.py", line 82, in main
    wfmanager.run()
  File "/home/ndemitri/.edm/envs/force-py36/lib/python3.6/site-packages/envisage/ui/tasks/tasks_application.py", line 140, in run
    self._create_windows()
  File "/home/ndemitri/.edm/envs/force-py36/lib/python3.6/site-packages/envisage/ui/tasks/tasks_application.py", line 305, in _create_windows
    restore=self.always_use_default_layout)
  File "/home/ndemitri/repos/force/master/force-wfmanager/force_wfmanager/wfmanager.py", line 71, in create_window
    layout, not restore, **traits
  File "/home/ndemitri/.edm/envs/force-py36/lib/python3.6/site-packages/envisage/ui/tasks/tasks_application.py", line 223, in create_window
    layout = self._restore_layout_from_state(layout)
  File "/home/ndemitri/.edm/envs/force-py36/lib/python3.6/site-packages/envisage/ui/tasks/tasks_application.py", line 351, in _restore_layout_from_state
    match.active_task = layout.get_active_task()
  File "/home/ndemitri/.edm/envs/force-py36/lib/python3.6/site-packages/traits/trait_handlers.py", line 236, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The 'active_task' trait of a TaskWindowLayout instance must be a string, but a value of None <class 'NoneType'> was specified.
```
although I'm sure it used to work for me last week. I can't assure that the packages picked by `edm` haven't changed though.

**Comment by jjenthought** [comment]
I think this happens when a TraitsUI app tries and fails to write an application_memento file (lives here on my pc: .enthought/force_wfmanager.wfmanager/tasks/qt4/). I think it uses that file to restore your layout to what it was when you last closed it, but if that file is broken it crashes. I think deleting the file will make things work again, but maybe we should try and catch this error and just make it load a default layout if the file is broken?

**Comment by nicolasap-dm** [comment]
Thanks! I confirm that removing that file has solved the issue!

I'm opening a new one to remind ourselves to do something about this.
